export const DEFAULT_CATEGORIES: { name: string; type: "expense" | "income"; color: string }[] = [
  { name: "Moradia", type: "expense", color: "#6366f1" },
  { name: "Alimentação", type: "expense", color: "#f97316" },
  { name: "Mercado", type: "expense", color: "#eab308" },
  { name: "Transporte", type: "expense", color: "#0ea5e9" },
  { name: "Saúde", type: "expense", color: "#ef4444" },
  { name: "Educação", type: "expense", color: "#8b5cf6" },
  { name: "Lazer", type: "expense", color: "#ec4899" },
  { name: "Assinaturas", type: "expense", color: "#14b8a6" },
  { name: "Cartão de crédito", type: "expense", color: "#f43f5e" },
  { name: "Contas (luz, água, internet)", type: "expense", color: "#22c55e" },
  { name: "Dívidas e financiamentos", type: "expense", color: "#a16207" },
  { name: "Impostos e taxas", type: "expense", color: "#78716c" },
  { name: "Outros", type: "expense", color: "#64748b" },
  { name: "Salário", type: "income", color: "#16a34a" },
  { name: "Freelance", type: "income", color: "#0d9488" },
  { name: "Investimentos", type: "income", color: "#2563eb" },
  { name: "Outras receitas", type: "income", color: "#65a30d" },
];
